import { User, Device, Curriculum, TenantConfig, DashboardStats, AtRiskLearner, ConsentRecord, AuditLogItem } from './types';

export const mockDashboardStats: DashboardStats = {
  active_learners: 12,
  total_learners: 15,
  sessions_this_week: 48,
  sessions_completed: 42,
  open_escalations: 2,
  resolved_escalations: 8,
  avg_mastery_pct: 65,
  devices_online: 8,
  devices_total: 10,
};

export const mockAtRiskLearners: AtRiskLearner[] = [
  {
    learner_id: 'learner-001',
    name: 'Ahmed Khan',
    email: 'ahmed@learnos.pk',
    grade: 'Grade 6',
    sessions_completed: 2,
    sessions_total: 6,
    open_escalations: 1,
    avg_mastery_pct: 35,
    risk_reason: 'Open Mentor Escalation',
  },
  {
    learner_id: 'learner-002',
    name: 'Sara Malik',
    email: 'sara@learnos.pk',
    grade: 'Grade 7',
    sessions_completed: 1,
    sessions_total: 5,
    open_escalations: 0,
    avg_mastery_pct: 38,
    risk_reason: 'Low Attendance Rate (<60%)',
  },
];

export const mockUsers: User[] = [
  {
    id: 'learner-001',
    email: 'ahmed@learnos.pk',
    name: 'Ahmed Khan',
    role: 'learner',
    tenant_id: 'tenant-001',
    is_active: true,
    created_at: '2026-07-01T09:00:00Z',
    grade: 'Grade 6',
    consent_given: true,
    guardian_id: 'parent-001',
    guardian_name: 'Tariq Khan',
    mentor_name: 'Ms. Nadia',
  },
  {
    id: 'learner-002',
    email: 'sara@learnos.pk',
    name: 'Sara Malik',
    role: 'learner',
    tenant_id: 'tenant-001',
    is_active: true,
    created_at: '2026-07-05T10:30:00Z',
    grade: 'Grade 7',
    consent_given: true,
    guardian_id: 'parent-002',
    guardian_name: 'Zainab Malik',
    mentor_name: 'Ms. Nadia',
  },
  {
    id: 'mentor-001',
    email: 'nadia@learnos.pk',
    name: 'Ms. Nadia',
    role: 'mentor',
    tenant_id: 'tenant-001',
    is_active: true,
    created_at: '2026-06-15T08:00:00Z',
  },
  {
    id: 'parent-001',
    email: 'tariq@gmail.com',
    name: 'Tariq Khan',
    role: 'parent',
    tenant_id: 'tenant-001',
    is_active: true,
    created_at: '2026-07-01T08:45:00Z',
  },
  {
    id: 'admin-001',
    email: 'admin@learnos.pk',
    name: 'Centre Admin',
    role: 'admin',
    tenant_id: 'tenant-001',
    is_active: true,
    created_at: '2026-06-01T00:00:00Z',
  },
];

export const mockDevices: Device[] = [
  {
    id: 'dev-001',
    name: 'Room 1 PC - Station 1',
    room: 'Room 1',
    tenant_id: 'tenant-001',
    device_token: '9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a',
    platform: 'windows',
    os_version: 'Windows 11 Pro Kiosk',
    app_version: '1.2.0',
    is_active: true,
    registered_at: '2026-07-10T09:00:00Z',
    last_seen_at: new Date(Date.now() - 3 * 60000).toISOString(),
  },
  {
    id: 'dev-002',
    name: 'Room 1 PC - Station 2',
    room: 'Room 1',
    tenant_id: 'tenant-001',
    device_token: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    platform: 'windows',
    os_version: 'Windows 11 Pro Kiosk',
    app_version: '1.2.0',
    is_active: true,
    registered_at: '2026-07-10T09:15:00Z',
    last_seen_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: 'dev-003',
    name: 'Room 2 Laptop (Offline)',
    room: 'Room 2',
    tenant_id: 'tenant-001',
    device_token: '3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d',
    platform: 'windows',
    os_version: 'Windows 10 Kiosk',
    app_version: '1.1.5',
    is_active: false,
    registered_at: '2026-06-20T11:00:00Z',
    last_seen_at: '2026-07-20T16:30:00Z',
  },
];

export const mockCurricula: Curriculum[] = [
  {
    id: 'curr-pnc-2006',
    code: 'PNC-2006',
    name: 'Pakistan National Curriculum (2006)',
    country: 'Pakistan',
    description: 'National Curriculum for Mathematics (Grades 6-8)',
    version: '2006.1',
  },
  {
    id: 'curr-cambridge-lower',
    code: 'CAMB-SEC-1',
    name: 'Cambridge Lower Secondary Mathematics',
    country: 'International',
    description: 'Cambridge Secondary 1 Mathematics framework (Stages 7-9)',
    version: '2023.2',
  },
];

export const mockTenantConfig: TenantConfig = {
  tenant_id: 'tenant-001',
  active_curriculum_id: 'curr-pnc-2006',
  active_curriculum_name: 'Pakistan National Curriculum (2006)',
  active_subjects: ['Mathematics'],
  grade_min: 6,
  grade_max: 8,
  settings: {
    kiosk_mode_strict: true,
    session_time_limit_min: 60,
  },
};

export const mockConsentRecords: ConsentRecord[] = [
  {
    learner_id: 'learner-001',
    learner_name: 'Ahmed Khan',
    learner_email: 'ahmed@learnos.pk',
    grade: 'Grade 6',
    guardian_id: 'parent-001',
    guardian_name: 'Tariq Khan',
    guardian_email: 'tariq@gmail.com',
    consent_given: true,
    consent_given_at: '2026-07-01T09:00:00Z',
  },
  {
    learner_id: 'learner-002',
    learner_name: 'Sara Malik',
    learner_email: 'sara@learnos.pk',
    grade: 'Grade 7',
    guardian_id: 'parent-002',
    guardian_name: 'Zainab Malik',
    guardian_email: 'zainab@gmail.com',
    consent_given: true,
    consent_given_at: '2026-07-05T10:30:00Z',
  },
];

export const mockAuditLogs: AuditLogItem[] = [
  {
    id: 'audit-001',
    actor_id: 'admin-001',
    actor_name: 'Centre Admin',
    actor_role: 'admin',
    action: 'user.create',
    resource_type: 'user',
    result: 'success',
    payload_summary: 'Created user "Ahmed Khan" (learner)',
    created_at: '2026-07-22T11:20:00Z',
  },
  {
    id: 'audit-002',
    actor_id: 'admin-001',
    actor_name: 'Centre Admin',
    actor_role: 'admin',
    action: 'device.register',
    resource_type: 'device',
    result: 'success',
    payload_summary: 'Registered device "Room 1 PC - Station 1"',
    created_at: '2026-07-22T10:15:00Z',
  },
  {
    id: 'audit-003',
    actor_id: 'admin-001',
    actor_name: 'Centre Admin',
    actor_role: 'admin',
    action: 'config.activate_curriculum',
    resource_type: 'tenant_config',
    result: 'success',
    payload_summary: 'Activated curriculum "Pakistan National Curriculum (2006)"',
    created_at: '2026-07-21T14:30:00Z',
  },
];
