-- V011: Sessions & Session Tasks
-- A session is one learner's scheduled learning block at the centre.
-- Session tasks are the ordered to-do list for that session.

CREATE TABLE sessions (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id       UUID        NOT NULL REFERENCES users(id)    ON DELETE RESTRICT,
  tenant_id        UUID        NOT NULL REFERENCES tenants(id)  ON DELETE RESTRICT,
  mentor_id        UUID                 REFERENCES users(id)    ON DELETE SET NULL,
  device_id        UUID                 REFERENCES devices(id)  ON DELETE SET NULL,
  planned_at       DATE        NOT NULL,
  started_at       TIMESTAMPTZ,
  ended_at         TIMESTAMPTZ,
  status           VARCHAR(50) NOT NULL DEFAULT 'planned'
                     CHECK (status IN ('planned','active','completed','abandoned')),
  session_goal     TEXT,
  total_duration_min INT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_sessions_learner ON sessions(learner_id, planned_at DESC);
CREATE INDEX idx_sessions_tenant  ON sessions(tenant_id, planned_at DESC);
CREATE INDEX idx_sessions_active  ON sessions(tenant_id, status) WHERE status = 'active';

COMMENT ON TABLE  sessions             IS 'One row per learner session (planned or completed).';
COMMENT ON COLUMN sessions.planned_at  IS 'Calendar date the session was scheduled.';
COMMENT ON COLUMN sessions.session_goal IS 'Plain-language goal set at the start. Shown to learner and mentor.';

-- Ordered task list within a session (the session plan)
CREATE TABLE session_tasks (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id    UUID        NOT NULL REFERENCES sessions(id)     ON DELETE CASCADE,
  task_order    INT         NOT NULL,
  task_type     VARCHAR(50) NOT NULL
                  CHECK (task_type IN ('review','learn','practice','reflect','break','mentor_check')),
  title         TEXT        NOT NULL,
  competency_id UUID                 REFERENCES competencies(id) ON DELETE SET NULL,
  resource_id   UUID                 REFERENCES resources(id)    ON DELETE SET NULL,
  duration_min  INT,
  status        VARCHAR(50) NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','active','completed','skipped')),
  started_at    TIMESTAMPTZ,
  completed_at  TIMESTAMPTZ,
  notes         TEXT,
  UNIQUE (session_id, task_order)
);

CREATE INDEX idx_session_tasks_session ON session_tasks(session_id, task_order);

COMMENT ON TABLE  session_tasks           IS 'Ordered to-do list for a session. Generated by the session planner.';
COMMENT ON COLUMN session_tasks.task_type IS 'review | learn | practice | reflect | break | mentor_check';
