-- V017: Weekly Reports
-- Parent-facing weekly progress reports. Generated by the report service.
-- Stored as structured JSON for rendering in web/email/PDF.

CREATE TABLE weekly_reports (
  id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id          UUID         NOT NULL REFERENCES users(id)   ON DELETE RESTRICT,
  parent_id           UUID         NOT NULL REFERENCES users(id)   ON DELETE RESTRICT,
  tenant_id           UUID         NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  week_label          VARCHAR(20)  NOT NULL,   -- ISO week: '2026-W30'
  week_start          DATE         NOT NULL,
  week_end            DATE         NOT NULL,

  -- Report content (flexible JSON)
  report_data         JSONB        NOT NULL,   -- Full structured report

  -- Status
  status              VARCHAR(50)  NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft','ready','sent')),
  mentor_reviewed     BOOLEAN      NOT NULL DEFAULT false,
  mentor_reviewed_at  TIMESTAMPTZ,
  mentor_reviewer_id  UUID                  REFERENCES users(id) ON DELETE SET NULL,

  -- Delivery tracking
  email_sent_at       TIMESTAMPTZ,
  email_opened_at     TIMESTAMPTZ,
  viewed_at           TIMESTAMPTZ,

  generated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  UNIQUE (learner_id, week_label)
);

CREATE INDEX idx_reports_parent  ON weekly_reports(parent_id, week_start DESC);
CREATE INDEX idx_reports_learner ON weekly_reports(learner_id, week_start DESC);

COMMENT ON TABLE  weekly_reports             IS 'Plain-language weekly progress reports for parents/guardians.';
COMMENT ON COLUMN weekly_reports.report_data IS 'Full report structure: glance, summary, topics, confidence, etc.';
